language: python
python:
- 3.7
- 3.6
- 3.5
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: purpleviolet
  password:
      secure: "pcSujRTEJawve2fYXSJnjWv3rbqwkZdQmQ+TC+fzbY5i9kO74vAdModyq94abBCueEsFxyHCAVxy38gj/uA1dQms16jrOlwdCzDiz2T7Anawdsa64Ul8W82nBlmvCSd76sYyppteI21WPAInP+09e4cFVY0HXGg5cj3LfmfgNpt9kmLwiNKwIriJEIOKfOr33iXYi6nVAACHlDCbBKQQiTZjskJLK2SI7V8UOz0cFoPB1vuOmMi4if/GfzcNwiizWkN3WiInyzQqeqYWr0MBHIw9+k6TPiujP0a3uXBOZOZZGZE8jMXx8jIPVo50OXkU2Xs7BRslTlur15N54eRmqSWbc1HrY3WWy9jodumOE0zYXKOVXUXpsLh+WDfWNcbZHbn6zZz2WD4s/I7Iop0RmQwvTsA9sj/BhmsLBiqXt41/I54v8RIm1jOdSFVC8UvuXnNrlwIIiesMnRV9pSWTSkr3iadTPGTKizr3y0A4awGpkfSUnXQB6rsrEfnrDpw7nvQW2Zo2dE37fJmpFk+PwnhffeC6mw+TJulca8l153W0KxcUrnZzTb7G3GF4THNcdxcT2XNbYLDTUYCHU5kbMOEncSkzL3bA2jrR2MxcmIKaKryfxnr89v8VqBgjv/Iev79MmvjYVWwXlg5cWRfYr/c+twiZe/OopVktzAJ1ydE="
  on:
    tags: true
    repo: purpleviolet/flattenit
    python: 3.7
